# Generated by Django 5.1.7 on 2025-03-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='user',
        ),
    ]
