# Generated by Django 5.1.7 on 2025-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_apikey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
